baseURL: "https://guillaumeberry.github.io/notes/"
languageCode: "en-uk"
title: "Guillaume Berry — notes"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
